---
AWSTemplateFormatVersion: "2010-09-09"
Description: ""

Parameters:
  LaunchTemplateVersionNumber:
    Default: 1
    Type: String

Resources:
  WebServerVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsSupport: false
      EnableDnsHostnames: false
      InstanceTenancy: dedicated
      Tags:
       - Key: stack
         Value: production

  WebServerSubnet:
    Type: AWS::EC2::Subnet
    Properties:
       CidrBlock: 10.0.1.0/24
       MapPublicIpOnLaunch: true
       VpcId:
         Ref: WebServerVPC

  WebServerInternetGateway:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
      - Key: stack
        Value: production

  WebserverIGWandVPCAttachment:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      InternetGatewayId:
        Ref: WebServerInternetGateway
      VpcId:
        Ref: WebServerVPC

  WebServerRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId:
        Ref: WebServerVPC
      Tags:
      - Key: stack
        Value: production

  WebServerSubnetRouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId:
        Ref: WebServerRouteTable
      SubnetId:
        Ref: WebServerSubnet

  WebServerRoute:
    Type: AWS::EC2::Route
    DependsOn: WebServerInternetGateway
    Properties:
       RouteTableId:
         Ref: WebServerRouteTable
       DestinationCidrBlock: 0.0.0.0/0
       GatewayId:
         Ref: WebServerInternetGateway

  InstanceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Open HTTP (port 80) and SSH (port 22)
      VpcId: !Ref WebServerVPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0

  WebServerEC2LaunchTemplate:
    Type: AWS::EC2::LaunchTemplate
    Properties:
      LaunchTemplateData:
        ImageId: ami-083ac7c7ecf9bb9b0
        InstanceType: t3.micro
        KeyName: test_key_pair
        NetworkInterfaces:
          - DeviceIndex: 0
            Groups:
              - Ref: InstanceSecurityGroup
            SubnetId:
              Ref: WebServerSubnet
            DeleteOnTermination: true
      LaunchTemplateName: WebServer_EC2_LaunchTemplate

  AutoScalingGroup:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      MinSize: '2'
      MaxSize: '5'
      DesiredCapacity: '3'
      LaunchTemplate:
        LaunchTemplateId: !Ref WebServerEC2LaunchTemplate
        Version: !Ref LaunchTemplateVersionNumber
      VPCZoneIdentifier:
        - Ref: WebServerSubnet
